# Generated by Django 4.2 on 2023-06-19 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('direct', '0002_livestream'),
    ]

    operations = [
        migrations.AddField(
            model_name='livestream',
            name='body',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='livestream',
            name='date',
            field=models.DateTimeField(editable=False, null=True),
        ),
        migrations.AddField(
            model_name='livestream',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
