# Generated by Django 4.2 on 2023-06-06 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('quiz', '0002_remove_quizzes_time_limit_mins'),
    ]

    operations = [
        migrations.AddField(
            model_name='quizzes',
            name='time_limit_mins',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
