# Generated by Django 4.2 on 2023-05-20 13:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_remove_comment_article_comment_chair'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='chair',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='blog.chair'),
        ),
    ]
