# Generated by Django 4.2 on 2023-05-24 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_alter_comment_chair'),
    ]

    operations = [
        migrations.AddField(
            model_name='chair',
            name='file',
            field=models.FileField(blank=True, null=True, upload_to='Files'),
        ),
    ]
