# Generated by Django 4.2 on 2023-05-28 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_click'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chair',
            name='image',
            field=models.ImageField(blank=True, default='chair-default.jpg', upload_to='chair_pics'),
        ),
    ]
