# Generated by Django 4.2 on 2023-05-29 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_alter_category_image_alter_chair_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Admin',
            fields=[
                ('AdminId', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('AdminPass', models.CharField(max_length=60)),
            ],
            options={
                'db_table': 'FP_Admin',
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('CartId', models.AutoField(primary_key=True, serialize=False)),
                ('CustEmail', models.CharField(max_length=50)),
                ('FoodId', models.CharField(max_length=50)),
                ('FoodQuant', models.CharField(max_length=10)),
            ],
            options={
                'db_table': 'FP_Cart',
            },
        ),
        migrations.CreateModel(
            name='Cust',
            fields=[
                ('CustId', models.AutoField(primary_key=True, serialize=False)),
                ('CustFName', models.CharField(max_length=30)),
                ('CustLName', models.CharField(max_length=30)),
                ('CustCont', models.CharField(max_length=10)),
                ('CustEmail', models.CharField(max_length=50)),
                ('CustPass', models.CharField(max_length=60)),
                ('Address', models.CharField(default='', max_length=150)),
            ],
            options={
                'db_table': 'FP_Cust',
            },
        ),
        migrations.CreateModel(
            name='Food',
            fields=[
                ('FoodId', models.AutoField(primary_key=True, serialize=False)),
                ('FoodName', models.CharField(max_length=30)),
                ('FoodCat', models.CharField(max_length=30)),
                ('FoodPrice', models.FloatField(max_length=15)),
                ('FoodImage', models.ImageField(default='', upload_to='media')),
            ],
            options={
                'db_table': 'FP_Food',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('OrderId', models.AutoField(primary_key=True, serialize=False)),
                ('CustEmail', models.CharField(max_length=30)),
                ('OrderDate', models.CharField(max_length=40)),
                ('TotalBill', models.FloatField(max_length=50)),
            ],
            options={
                'db_table': 'FP_Order',
            },
        ),
    ]
