# Generated by Django 4.2 on 2023-05-29 09:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_admin_cart_cust_food_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Admin',
        ),
        migrations.DeleteModel(
            name='Cart',
        ),
        migrations.DeleteModel(
            name='Cust',
        ),
        migrations.DeleteModel(
            name='Food',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
