# Generated by Django 4.2 on 2023-06-27 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_click'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='article',
            unique_together={('title', 'category')},
        ),
        migrations.DeleteModel(
            name='Click',
        ),
    ]
