# Generated by Django 4.2 on 2023-06-27 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_alter_article_unique_together_delete_click'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='course',
            unique_together={('title', 'article')},
        ),
    ]
