# Generated by Django 4.2 on 2023-06-07 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0004_auto_20210620_0158'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch_category',
            name='title',
            field=models.CharField(max_length=100, unique='title', verbose_name='Title'),
        ),
    ]
