# Generated by Django 4.2 on 2023-06-07 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0005_alter_batch_category_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='batch_category',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
    ]
