# Generated by Django 4.2 on 2023-06-10 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_remove_profile_user_chair_enrolled_delete_click'),
        ('classroom', '0008_rename_category_course_table'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='category',
            unique_together=None,
        ),
        migrations.AlterUniqueTogether(
            name='lecture',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='lecture',
            name='article',
        ),
        migrations.RemoveField(
            model_name='lecture',
            name='author',
        ),
        migrations.AlterUniqueTogether(
            name='mem',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='mem',
            name='author',
        ),
        migrations.RemoveField(
            model_name='mem',
            name='rep',
        ),
        migrations.AlterUniqueTogether(
            name='rep',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='rep',
            name='author',
        ),
        migrations.RemoveField(
            model_name='rep',
            name='room',
        ),
        migrations.AlterUniqueTogether(
            name='room',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='room',
            name='author',
        ),
        migrations.RemoveField(
            model_name='room',
            name='subject',
        ),
        migrations.AlterUniqueTogether(
            name='subject',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='subject',
            name='author',
        ),
        migrations.RemoveField(
            model_name='subject',
            name='lecture',
        ),
        migrations.AlterUniqueTogether(
            name='table',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='table',
            name='author',
        ),
        migrations.RemoveField(
            model_name='table',
            name='mem',
        ),
        migrations.AlterField(
            model_name='course',
            name='table',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.table'),
        ),
        migrations.DeleteModel(
            name='Article',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
        migrations.DeleteModel(
            name='Lecture',
        ),
        migrations.DeleteModel(
            name='Mem',
        ),
        migrations.DeleteModel(
            name='Rep',
        ),
        migrations.DeleteModel(
            name='Room',
        ),
        migrations.DeleteModel(
            name='Subject',
        ),
        migrations.DeleteModel(
            name='Table',
        ),
    ]
