# Generated by Django 4.2 on 2023-06-14 09:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_click'),
        ('classroom', '0009_alter_category_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='table',
        ),
        migrations.AddField(
            model_name='course',
            name='mem',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='blog.mem'),
        ),
    ]
