# Generated by Django 4.2 on 2023-06-14 09:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0016_click'),
        ('classroom', '0011_alter_course_mem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='mem',
            field=models.ForeignKey(default='1', on_delete=django.db.models.deletion.CASCADE, to='blog.mem'),
        ),
    ]
